// generated by Fast Light User Interface Designer (fluid) version 1.0309

#ifndef MainWindow_h
#define MainWindow_h
#include <FL/Fl.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Table.H>
#include <FL/Fl_Button.H>

class UserInterface : public Fl_Group {
public:
  UserInterface(int X, int Y, int W, int H, const char *L = 0);
};
#endif
